### ISSUE TITLE
[TokenSolver] captchasolver test module error

### ISSUE THREAD

**Issue by UnixCr3wR0x** [M-Zubair10/CaptchaXpert#3]
well i have been trying to run the test module on this lib but i get this errors 

```
2023-04-25 01:30:32,368 - WDM - INFO - ====== WebDriver manager ======
2023-04-25 01:30:33,324 - WDM - INFO - Get LATEST chromedriver version for google-chrome 112.0.5615
2023-04-25 01:30:34,399 - WDM - INFO - Driver [C:\Users\Un1xCr3w\.wdm\drivers\chromedriver\win32\112.0.5615\chromedriver.exe] found in cache
2023-04-25 01:30:36,186 - __main__ - INFO - Success initialized!
2023-04-25 01:30:36,205 - api - INFO - [CaptchaSolver] Solving recaptcha_v2
2023-04-25 01:30:36,206 - api.solutions.common - INFO - ===== WebDriver-MultiWait =====
2023-04-25 01:30:36,206 - api.solutions.common - DEBUG - [MultiWait] Locators: [('xpath', '//iframe[@title="Widget containing checkbox for hCaptcha security challenge"]'), ('xpath', '//iframe[@title="Main content of the hCaptcha challenge"]'), ('xpath', '//iframe[@title="reCAPTCHA"]'), ('xpath', '//iframe[contains(@title, "recaptcha")]'), ('xpath', '//iframe[@title="reCAPTCHA" and contains(@src, "invisible")]')]
2023-04-25 01:30:36,208 - api.solutions.common - DEBUG - [MultiWait] Max-Polls: 100
2023-04-25 01:30:41,344 - api.solutions.common - DEBUG - [MultiWait] Element found at ('xpath', '//iframe[@title="reCAPTCHA"]')
2023-04-25 01:30:41,503 - api.solutions.recaptcha.common - DEBUG - Finding real hook frame
2023-04-25 01:30:41,580 - api.solutions.recaptcha.common - DEBUG - Real hook frame found
2023-04-25 01:30:41,582 - api.solutions.recaptcha.recaptcha_v2 - DEBUG - [RecaptchaV2Challenger] - Challenge handling
2023-04-25 01:30:41,582 - api.solutions.recaptcha.recaptcha_v2 - DEBUG - Challenge handling
2023-04-25 01:30:41,583 - api.solutions.common - INFO - ===== WebDriver-MultiWait =====
2023-04-25 01:30:41,583 - api.solutions.common - DEBUG - [MultiWait] Locators: [<bound method RecaptchaUtils.anti_checkbox of <api.solutions.recaptcha.recaptcha_v2.RecaptchaV2 object at 0x0000028D0ADA2E20>>, <bound method RecaptchaUtils.is_banner_visible of <api.solutions.recaptcha.recaptcha_v2.RecaptchaV2 object at 0x0000028D0ADA2E20>>, <bound method RecaptchaUtils.recaptcha_response of <api.solutions.recaptcha.recaptcha_v2.RecaptchaV2 object at 0x0000028D0ADA2E20>>, <function RecaptchaUtils.__init__.<locals>.<lambda> at 0x0000028D0ADA4F70>]
2023-04-25 01:30:41,584 - api.solutions.common - DEBUG - [MultiWait] Max-Polls: 100
2023-04-25 01:30:41,637 - api.solutions.common - DEBUG - [Click-JS] Element clicked using javascript executor
2023-04-25 01:30:41,746 - api.solutions.recaptcha.common - DEBUG - Clicked checkbox
2023-04-25 01:30:41,748 - api.solutions.common - INFO - ===== WebDriver-MultiWait =====
2023-04-25 01:30:41,748 - api.solutions.common - DEBUG - [MultiWait] Locators: [<function RecaptchaV2.solve.<locals>.<lambda> at 0x0000028D0B5D2280>, <bound method RecaptchaUtils.is_banner_visible of <api.solutions.recaptcha.recaptcha_v2.RecaptchaV2 object at 0x0000028D0ADA2E20>>, <bound method RecaptchaUtils.recaptcha_response of <api.solutions.recaptcha.recaptcha_v2.RecaptchaV2 object at 0x0000028D0ADA2E20>>, <function RecaptchaUtils.__init__.<locals>.<lambda> at 0x0000028D0ADA4F70>]
2023-04-25 01:30:41,749 - api.solutions.common - DEBUG - [MultiWait] Max-Polls: 100
2023-04-25 01:30:43,981 - api.solutions.recaptcha.recaptcha_v2 - DEBUG - [RecaptchaV2Challenger] - Response: True
2023-04-25 01:30:43,981 - api.solutions.recaptcha.recaptcha_v2 - DEBUG - Response: True
2023-04-25 01:30:43,983 - api - INFO - [CaptchaSolver] Type: recaptcha_v2 | Returned: True | Time consumed 7.778 seconds
2023-04-25 01:30:43,986 - __main__ - INFO - Response: True in 7.7987000942230225
2023-04-25 01:30:43,998 - api - INFO - [CaptchaSolver] Solving recaptcha_v2
2023-04-25 01:30:43,999 - api.solutions.common - INFO - ===== WebDriver-MultiWait =====
2023-04-25 01:30:43,999 - api.solutions.common - DEBUG - [MultiWait] Locators: [('xpath', '//iframe[@title="Widget containing checkbox for hCaptcha security challenge"]'), ('xpath', '//iframe[@title="Main content of the hCaptcha challenge"]'), ('xpath', '//iframe[@title="reCAPTCHA"]'), ('xpath', '//iframe[contains(@title, "recaptcha")]'), ('xpath', '//iframe[@title="reCAPTCHA" and contains(@src, "invisible")]')]
2023-04-25 01:30:44,000 - api.solutions.common - DEBUG - [MultiWait] Max-Polls: 100
2023-04-25 01:30:46,509 - api.solutions.common - DEBUG - [MultiWait] Element found at ('xpath', '//iframe[@title="reCAPTCHA"]')
2023-04-25 01:30:46,535 - api.solutions.recaptcha.common - DEBUG - Finding real hook frame
2023-04-25 01:30:46,600 - api.solutions.recaptcha.common - DEBUG - Real hook frame found
2023-04-25 01:30:46,601 - api.solutions.recaptcha.recaptcha_v2 - DEBUG - [RecaptchaV2Challenger] - Challenge handling
2023-04-25 01:30:46,601 - api.solutions.recaptcha.recaptcha_v2 - DEBUG - Challenge handling
2023-04-25 01:30:46,601 - api.solutions.common - INFO - ===== WebDriver-MultiWait =====
2023-04-25 01:30:46,601 - api.solutions.common - DEBUG - [MultiWait] Locators: [<bound method RecaptchaUtils.anti_checkbox of <api.solutions.recaptcha.recaptcha_v2.RecaptchaV2 object at 0x0000028D0ADA2E20>>, <bound method RecaptchaUtils.is_banner_visible of <api.solutions.recaptcha.recaptcha_v2.RecaptchaV2 object at 0x0000028D0ADA2E20>>, <bound method RecaptchaUtils.recaptcha_response of <api.solutions.recaptcha.recaptcha_v2.RecaptchaV2 object at 0x0000028D0ADA2E20>>, <function RecaptchaUtils.__init__.<locals>.<lambda> at 0x0000028D0ADA4F70>]
2023-04-25 01:30:46,602 - api.solutions.common - DEBUG - [MultiWait] Max-Polls: 100
2023-04-25 01:30:46,644 - api.solutions.common - DEBUG - [Click-JS] Element clicked using javascript executor
2023-04-25 01:30:46,743 - api.solutions.recaptcha.common - DEBUG - Clicked checkbox
2023-04-25 01:30:46,746 - api.solutions.common - INFO - ===== WebDriver-MultiWait =====
2023-04-25 01:30:46,746 - api.solutions.common - DEBUG - [MultiWait] Locators: [<function RecaptchaV2.solve.<locals>.<lambda> at 0x0000028D0B5D2310>, <bound method RecaptchaUtils.is_banner_visible of <api.solutions.recaptcha.recaptcha_v2.RecaptchaV2 object at 0x0000028D0ADA2E20>>, <bound method RecaptchaUtils.recaptcha_response of <api.solutions.recaptcha.recaptcha_v2.RecaptchaV2 object at 0x0000028D0ADA2E20>>, <function RecaptchaUtils.__init__.<locals>.<lambda> at 0x0000028D0ADA4F70>]
2023-04-25 01:30:46,747 - api.solutions.common - DEBUG - [MultiWait] Max-Polls: 100
2023-04-25 01:30:48,973 - api.solutions.recaptcha.recaptcha_v2 - DEBUG - [RecaptchaV2Challenger] - Response: True
2023-04-25 01:30:48,973 - api.solutions.recaptcha.recaptcha_v2 - DEBUG - Response: True
2023-04-25 01:30:48,974 - api - INFO - [CaptchaSolver] Type: recaptcha_v2 | Returned: True | Time consumed 4.975 seconds
2023-04-25 01:30:48,977 - __main__ - INFO - Response: True in 4.990962266921997
2023-04-25 01:30:48,987 - api - INFO - [CaptchaSolver] Solving recaptcha_v2
2023-04-25 01:30:48,988 - api.solutions.common - INFO - ===== WebDriver-MultiWait =====
2023-04-25 01:30:48,989 - api.solutions.common - DEBUG - [MultiWait] Locators: [('xpath', '//iframe[@title="Widget containing checkbox for hCaptcha security challenge"]'), ('xpath', '//iframe[@title="Main content of the hCaptcha challenge"]'), ('xpath', '//iframe[@title="reCAPTCHA"]'), ('xpath', '//iframe[contains(@title, "recaptcha")]'), ('xpath', '//iframe[@title="reCAPTCHA" and contains(@src, "invisible")]')]
2023-04-25 01:30:48,990 - api.solutions.common - DEBUG - [MultiWait] Max-Polls: 100
2023-04-25 01:30:51,986 - api.solutions.common - DEBUG - [MultiWait] Element found at ('xpath', '//iframe[@title="reCAPTCHA"]')
2023-04-25 01:30:52,008 - api.solutions.recaptcha.common - DEBUG - Finding real hook frame
2023-04-25 01:30:52,079 - api.solutions.recaptcha.common - DEBUG - Real hook frame found
2023-04-25 01:30:52,079 - api.solutions.recaptcha.recaptcha_v2 - DEBUG - [RecaptchaV2Challenger] - Challenge handling
2023-04-25 01:30:52,079 - api.solutions.recaptcha.recaptcha_v2 - DEBUG - Challenge handling
2023-04-25 01:30:52,080 - api.solutions.common - INFO - ===== WebDriver-MultiWait =====
2023-04-25 01:30:52,082 - api.solutions.common - DEBUG - [MultiWait] Locators: [<bound method RecaptchaUtils.anti_checkbox of <api.solutions.recaptcha.recaptcha_v2.RecaptchaV2 object at 0x0000028D0ADA2E20>>, <bound method RecaptchaUtils.is_banner_visible of <api.solutions.recaptcha.recaptcha_v2.RecaptchaV2 object at 0x0000028D0ADA2E20>>, <bound method RecaptchaUtils.recaptcha_response of <api.solutions.recaptcha.recaptcha_v2.RecaptchaV2 object at 0x0000028D0ADA2E20>>, <function RecaptchaUtils.__init__.<locals>.<lambda> at 0x0000028D0ADA4F70>]
2023-04-25 01:30:52,083 - api.solutions.common - DEBUG - [MultiWait] Max-Polls: 100
2023-04-25 01:30:52,139 - api.solutions.common - DEBUG - [Click-JS] Element clicked using javascript executor
2023-04-25 01:30:52,240 - api.solutions.recaptcha.common - DEBUG - Clicked checkbox
2023-04-25 01:30:52,246 - api.solutions.common - INFO - ===== WebDriver-MultiWait =====
2023-04-25 01:30:52,246 - api.solutions.common - DEBUG - [MultiWait] Locators: [<function RecaptchaV2.solve.<locals>.<lambda> at 0x0000028D0B5D21F0>, <bound method RecaptchaUtils.is_banner_visible of <api.solutions.recaptcha.recaptcha_v2.RecaptchaV2 object at 0x0000028D0ADA2E20>>, <bound method RecaptchaUtils.recaptcha_response of <api.solutions.recaptcha.recaptcha_v2.RecaptchaV2 object at 0x0000028D0ADA2E20>>, <function RecaptchaUtils.__init__.<locals>.<lambda> at 0x0000028D0ADA4F70>]
2023-04-25 01:30:52,247 - api.solutions.common - DEBUG - [MultiWait] Max-Polls: 100
2023-04-25 01:30:53,300 - api.solutions.recaptcha.common - DEBUG - Label banner is visible
2023-04-25 01:30:53,301 - api.solutions.recaptcha.common - DEBUG - Finding real challenge frame
2023-04-25 01:30:53,377 - api.solutions.recaptcha.common - DEBUG - Real challenge frame found
2023-04-25 01:30:53,436 - api.solutions.recaptcha.recaptcha_v2 - DEBUG - [RecaptchaV2Challenger] - Switching to challenge frame
2023-04-25 01:30:53,436 - api.solutions.recaptcha.recaptcha_v2 - DEBUG - Switching to challenge frame
2023-04-25 01:30:53,497 - api.solutions.recaptcha.recaptcha_v2 - DEBUG - [RecaptchaV2Challenger] - Label found - traffic lights
2023-04-25 01:30:53,497 - api.solutions.recaptcha.recaptcha_v2 - DEBUG - Label found - traffic lights
2023-04-25 01:30:53,832 - api.solutions.recaptcha.recaptcha_v2 - DEBUG - [RecaptchaV2Challenger] - Image element found
2023-04-25 01:30:53,832 - api.solutions.recaptcha.recaptcha_v2 - DEBUG - Image element found
2023-04-25 01:30:53,833 - api.solutions.recaptcha.common - DEBUG - Getting image in base64 format
2023-04-25 01:30:54,203 - api.solutions.recaptcha.common - DEBUG - Success getting image in base64 format
2023-04-25 01:30:54,203 - api.solutions.recaptcha.recaptcha_v2 - DEBUG - [RecaptchaV2Challenger] - Resolving images...
2023-04-25 01:30:54,203 - api.solutions.recaptcha.recaptcha_v2 - DEBUG - Resolving images...
2023-04-25 01:30:56,232 - __main__ - INFO - ====== Results ======
Responses: [(True, 7.799), (True, 4.991)]
Counter: Counter({True: 2})
Time: 12.79
Traceback (most recent call last):
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1040, in _send_output
    self.send(msg)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 980, in send
    self.connect()
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000028D0B5E0D60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /resolve (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028D0B5E0D60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\code-base\my tools\CaptchaXpert\api\testcase.py", line 138, in <module>
    run_recaptcha_v2_test()
  File "E:\code-base\my tools\CaptchaXpert\api\testcase.py", line 56, in wrapper
    return n_tests(func, *args, **kwargs)
  File "E:\code-base\my tools\CaptchaXpert\api\testcase.py", line 71, in n_tests
    result = func(*args, **kwargs)
  File "E:\code-base\my tools\CaptchaXpert\api\testcase.py", line 83, in run_recaptcha_v2_test
    return solver.solve()
  File "E:\code-base\my tools\CaptchaXpert\api\__init__.py", line 29, in wrapper
    raise e
  File "E:\code-base\my tools\CaptchaXpert\api\__init__.py", line 25, in wrapper
    return func(self, *args, **kwargs)
  File "E:\code-base\my tools\CaptchaXpert\api\__init__.py", line 231, in solve
    self.RESPONSE = self.recaptcha_v2.RecaptchaV2(self.HOST, self.driver, self.wait, self.timeout,
  File "E:\code-base\my tools\CaptchaXpert\api\solutions\recaptcha\recaptcha_v2.py", line 153, in solve
    response = self._solve()
  File "E:\code-base\my tools\CaptchaXpert\api\solutions\recaptcha\recaptcha_v2.py", line 98, in _solve
    response = requests.post(f"{self.HOST}/resolve", json=data)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /resolve (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028D0B5E0D60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2023-04-25 01:30:56,617 - undetected_chromedriver.dprocess - DEBUG - cleaning up pid 11776 
2023-04-25 01:31:00,740 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028D0ADA2B80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f7575028a56e6a06f65d4239a70a7550
2023-04-25 01:31:04,825 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028D0AC8EC70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f7575028a56e6a06f65d4239a70a7550
2023-04-25 01:31:08,925 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028D0AB2DDC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f7575028a56e6a06f65d4239a70a7550
```

iam really sorry for this message but iam not python developer i cant quite understand the issue here 

i froze all the pip modules and reinstalled them all and for sure

**Comment by M-Zubair10** [comment]
This library communicate with webserver app at http://127.0.0.1:5000 that
resolve captcha images, make sure you first run that app in
CaptchaXpert/CaptchaSolver/app.py

This is because loading ml models in every module is time and resource
consuming, so we just load it once in the server app and then communicate
with it

Also make sure to check the release for new ml models for better accuracy
in recaptcha

Thanks

**Comment by M-Zubair10** [comment]
Also, check readme quickstart guide

One thing to make sure, this lib is pure python, however if you don't use
it you can still take advantage of captchasolver webserver for solving
images and write your preferred language api

**Comment by UnixCr3wR0x** [comment]
i just wanna know what is the payload that should be sent to this flast api endpoint

**Comment by M-Zubair10** [comment]
Kindly notice that there are two flask apps in lib, one for captcha images
solving named CaptchaResolver, all other apps depend on it, so you must run
it

And the second one is TokenSolver, which accept type of captcha as
recaptcha or hcaptcha, url of the target site and sitekey of captcha, and
return the captcha token

All payloads are written in test module in TokenSolver dir, kindly check
that

**Comment by UnixCr3wR0x** [comment]
iam getting this error : 
```
E:\code-base\CaptchaXpert\CaptchaResolver>python -m app
2023-04-27 03:18:54,477 - __main__ - INFO - Loading solutions...
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\code-base\CaptchaXpert\CaptchaResolver\app.py", line 24, in <module>
    from intercept import intercept
  File "E:\code-base\CaptchaXpert\CaptchaResolver\intercept.py", line 8, in <module>
    import cv2
  File "C:\Users\MAli\AppData\Roaming\Python\Python310\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\MAli\AppData\Roaming\Python\Python310\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "C:\Users\MAli\AppData\Roaming\Python\Python310\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\MAli\AppData\Roaming\Python\Python310\site-packages\cv2\gapi\__init__.py", line 301, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)

```

**Comment by UnixCr3wR0x** [comment]
@M-Zubair10 well first of all thanks a lot for thins handsome library i really liked it 
second of all iam facing a problem right now which is the accuarcy is low how can i increase it ?
3rd what is the desired payload if i wanna send the captcha label and base64 of all the images to memic the user interactions ?

thanks a lot for ur gr8 effort i believe this is the best python lib i have used in a while.

**Comment by M-Zubair10** [comment]
Sorry for my exam today, I will fix this tomorrow

**Comment by UnixCr3wR0x** [comment]
its ok good luck in ur exam i hope everything go well.

**Comment by M-Zubair10** [comment]
Payload for recaptcha

JsonDict{images: listofbase64images, label: current label of recaptcha,
grid: 4x4 or 3x3}

For improved accuracy, i am training new ml models using yolov8, check
releases

**Comment by UnixCr3wR0x** [comment]
good job , does the hcaptcha work the same way now ?

**Comment by M-Zubair10** [comment]
I currently rely on QIN2DIM hcaptcha solver and my priority is recaptcha
perfection, so all hcaptcha models are their models, in very short time
after my exams about within a month i will get perfection in hcaptcha too

Its payload is prompt, images

Also one more thing, check out the tokensolver app, it will solve captcha
in headless mode and give you token which you can inject easily to bypass it

**Comment by M-Zubair10** [comment]
Yes it solves now, check it out

**Comment by UnixCr3wR0x** [comment]
hello thanks a lot for ur gr8 effort but right now i dont know how to use after ur update 
iam running solver app and token app 
then iam try to make a post request to http://localhost:5000
with this payload 
`
{
    "domain": "https://accounts.hcaptcha.com/demo",
    "sitekey": "a5f74b19-9e45-40e0-b45d-47ff91b7a6c2",
    "type": "hcaptcha"
}
`

but iam getting 

`
<!doctype html>
<html lang=en>
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
`

is there anything wrong with my payload ?

**Comment by M-Zubair10** [comment]
Please note that domain is hcaptcha.com in this case

Its url in payload

**Comment by UnixCr3wR0x** [comment]
i know and i made this request
{
    "type": "hcaptcha",
    "domain":"nopecha.com",
    "sitekey": "b4c45857-0e23-48e6-9017-e28fff99ffb2"
}

and i got the responseId

but when i send get request like this
http://localhost:5004/response?id=2b48bc28-5ce2-49d8-abc9-e24ba7141d7e

iam getting 
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or
	there is an error in the application.</p>

**Comment by M-Zubair10** [comment]
Finally, I figured it out
I actually modified the seleniumbase lib and when you did pip install
seleniumbase you have the default one
Let me fix the dependency

Also, you can deploy it to the lambda function for faster processing

**Comment by UnixCr3wR0x** [comment]
yes please can u give me instructions on how to deploy it please , sorry i know this is a lot to ask but iam really trying to get my feet into python development
